### PR TITLE
Application Guides - Luverne

### PR DESCRIPTION
**Pull request by ninnemana**
Currently there is no application guide section for Luverne like ARIES: http://ariesautomotive.com/appguides.

@1brandeja5 has populated `Finish` as a product attribute for all Luverne items, so we can pivot out application data onto an application table. There are two adjustments that will have to be made:

1. Luverne app data is in year/make/model/body/fuel/cab/box format.
2. There is no Godzilla (flat collection) data structure, so we'll have to pull the application data directly off the product collection and aggregate it into groups using the category hierarchy.

### CODE REVIEW

**Comment by ninnemana** [comment]
@1brandeja5 are we meeting with luverne anytime soon to get their sign-off?

**Comment by 1brandeja5** [comment]
whenever you want :)

**Comment by 1brandeja5** [comment]
Here are the first 3 approved app guides
[Tuff Guard 3 IN Van Bumper Guards.xlsx](https://github.com/aries-auto/ariesautomotive/files/678990/Tuff.Guard.3.IN.Van.Bumper.Guards.xlsx)
[Prowler Max Grille Guards.xlsx](https://github.com/aries-auto/ariesautomotive/files/678991/Prowler.Max.Grille.Guards.xlsx)
[Tow Guards and Heat Shields.xlsx](https://github.com/aries-auto/ariesautomotive/files/678992/Tow.Guards.and.Heat.Shields.xlsx)

**Comment by ninnemana** [comment]
Looks like the 6 1/2" running board breaks the URL routing: http://localhost:3000/appguides/363/MegaStep%206%201/2%22%20Running%20Boards

**Comment by 1brandeja5** [comment]
Is that why it ended up being 6.5 Inch before?

**Comment by dgallegos** [comment]
We are not doing it this way.

**Pull request closed without merging**
