### PR TITLE
Refactor/noprod cats

### PR DESCRIPTION
**Pull request by ninnemana**
Removes products from category pages that are vehicle specific.

### CODE REVIEW

**Comment by aaronrodgersmoustache** [comment]
We should add the mud flap parts back onto the category page like Seat Defender. Even though these are no-drill on the Jeep Wrangler, they're designed to be universal and attach to virtually any truck or SUV.

**Comment by ninnemana** [comment]
http://admin.curtmfg.com/categories/335

screenshot 2016-02-12 09 43 18

Just have to toggle the "Vehicle Specific" flag.

**Comment by aaronrodgersmoustache** [comment]
If I turn that off, will the vehicle lookup still show them fitting the Jeep Wrangler?

**Comment by ninnemana** [comment]
Yup, the only impact will be that products show in that category.

**Pull request merged**
