### PR TITLE
Application Guide Restyling

### PR DESCRIPTION
**Pull request by ninnemana**
Currently the [Application Guides](http://www.ariesautomotive.com/appguides) navigation is based off the collections that we setup in MongoDB. Does this need to be a dynamically displayed application guide going forward or are we ok with linking to physical PDF/Excel documents for reference?

aries-application-guide-page-mockup

### CODE REVIEW

**Comment by ninnemana** [comment]
All of the application guide files have been updated in the admin by @1brandeja5. Once the merge conflicts are resolved, are we ready to go live? /cc @ngamer @ripienski @aaronrodgersmoustache

**Comment by 1brandeja5** [comment]
#appguidesforwhat #newproductstructure #whatsnext? looks very nice dev and marketing teams!!

**Comment by aaronrodgersmoustache** [comment]
The sort is still not working properly, but just for the Running Boards & Side Bars section.

**Comment by DavidVaini** [comment]
Updated the sort order in IAPI, got in touch with @aaronrodgersmoustache and the sort order is now working properly.

**Pull request merged**
