### PR TITLE
Refactor/catalog 249

### PR DESCRIPTION
**Pull request by WileESpaghetti**
Removed old catalogs
Updated 2017 calendar
Moved catalogs location

### CODE REVIEW

**Comment by ninnemana** [comment]
Can we achieve this with using `flexbox`? That way we can have a CSS only approach and don't need react properties for styling.

**Comment by WileESpaghetti** [comment]
I have my doubts, but I'll take a stab at it and see.

**Comment by WileESpaghetti** [comment]
Do you know how the component `.root` class names are being created? I need to change the `flex-direction` for the `.root` class from `src/components/home/Catalogs.scss` inside of `src/components/home/Marketing.scss`

**Comment by ninnemana** [comment]
They're being generated in webpack: https://github.com/aries-auto/ariesautomotive/blob/master/tools/webpack.config.js#L105. When I've needed to manipulate a child component from the parent I've always done it by referencing the DOM specifically.

Instead of 

```scss
div .Catalogs_root_3GX {

}
```
it ends up with

```scss
div > div:first-child {

}
```

**Pull request merged**
